base-webapp-tab/src/main/java/com/tmt/base/cms/entity/Article.java
package com.tmt.base.cms.entity;

import java.util.Date;
import java.util.List;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import org.apache.commons.lang3.StringUtils;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Node;

import com.google.common.collect.Lists;
import com.google.common.collect.Maps;
import com.tmt.base.cms.utils.CmsUtils;
import com.tmt.base.common.utils.FreemarkerUtils;
import com.tmt.base.common.utils.StringUtil3;
import com.tmt.base.system.entity.BaseEntity;

public class Article extends BaseEntity<String> {
    
	private static final long serialVersionUID = 1187002354311677153L;
	private static final Pattern IIIlllII = Pattern.compile("[,;\\.!?，；。！？]");
	
	private String categoryId;// 分类编号
    private String title;// 标题
    private String link;// 外部链接
    private String color;// 标题颜色（red：红色；green：绿色；blue：蓝色；yellow：黄色；orange：橙色）
    private String image;// 文章图片
    private String keywords;// 关键字
    private Integer weight;// 权重，越大越靠前
    private Date weightDate;// 权重期限，超过期限，将weight设置为0
    private Integer hits;// 点击数
    private String posid;// 推荐位，多选（1：首页焦点图；2：栏目页文章推荐；）
    private String customContentView;// 自定义内容视图
    private String viewConfig;	// 视图参数
    private String categoryName;//分类名称
    private ArticleData articleData;//文章副表,内容
    private Integer pageNumber;//内容是否分页显示
    
    public Integer getPageNumber() {
		return pageNumber;
	}
	public void setPageNumber(Integer pageNumber) {
		this.pageNumber = pageNumber;
	}
	public ArticleData getArticleData() {
		return articleData;
	}
	public void setArticleData(ArticleData articleData) {
		this.articleData = articleData;
	}
	public String getCategoryName() {
		return categoryName;
	}
	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}
	public String getViewConfig() {
		return viewConfig;
	}
	public void setViewConfig(String viewConfig) {
		this.viewConfig = viewConfig;
	}
	public String getCategoryId() {
		return categoryId;
	}
	public void setCategoryId(String categoryId) {
		this.categoryId = categoryId;
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public String getLink() {
		return link;
	}
	public void setLink(String link) {
		this.link = link;
	}
	public String getColor() {
		return color;
	}
	public void setColor(String color) {
		this.color = color;
	}
	public String getImage() {
		return image;
	}
	public void setImage(String image) {
		this.image = image;
	}
	public String getKeywords() {
		return keywords;
	}
	public void setKeywords(String keywords) {
		this.keywords = keywords;
	}
	public Integer getWeight() {
		return weight;
	}
	public void setWeight(Integer weight) {
		this.weight = weight;
	}
	public Date getWeightDate() {
		return weightDate;
	}
	public void setWeightDate(Date weightDate) {
		this.weightDate = weightDate;
	}
	public Integer getHits() {
		return hits;
	}
	public void setHits(Integer hits) {
		this.hits = hits;
	}
	public String getPosid() {
		return posid;
	}
	public void setPosid(String posid) {
		this.posid = posid;
	}
	public String getCustomContentView() {
		return customContentView;
	}
	public void setCustomContentView(String customContentView) {
		this.customContentView = customContentView;
	}
	
	public List<String> getPosidList() {
		List<String> list = Lists.newArrayList();
		if (posid != null){
			for (String s : StringUtils.split(posid, ",")) {
				list.add(s);
			}
		}
		return list;
	}
	
	public void setPosidList(List<Long> list) {
		posid = ","+StringUtils.join(list, ",")+",";
	}
	
	public String getContent(){
		if (this.pageNumber != null) {
			String[] arrayOfString = getPageContents();
			if (this.pageNumber.intValue() < 1)
				this.pageNumber = Integer.valueOf(1);
			if (this.pageNumber.intValue() > arrayOfString.length)
				this.pageNumber = Integer.valueOf(arrayOfString.length);
			return arrayOfString[(this.pageNumber.intValue() - 1)];
		}
		return this.articleData == null?"":this.articleData.getContent();
	}
	
	/**
	 * 文章可能是分页展示的
	 * @return
	 */
	public String[] getPageContents() {
		String content = this.articleData == null?"":this.articleData.getContent();
		if( StringUtil3.isEmpty(content)) {
			return new String[]{""};
		}
		List<String> contents = Lists.newArrayList();
		org.jsoup.nodes.Document localDocument = Jsoup.parse(content);
		List<Node> nodes = localDocument.body().childNodes();
		if( nodes != null) {
			int i = 0;
		    StringBuffer localStringBuffer = new StringBuffer();
		    for( Node node: nodes ){
		    	if( node instanceof org.jsoup.nodes.Element ) {
		    		localStringBuffer.append(((org.jsoup.nodes.Element)node).outerHtml());
		            i += ((org.jsoup.nodes.Element)node).text().length();
		            if (i >= 800){
		              contents.add(localStringBuffer.toString());
		              i = 0;
		              localStringBuffer.setLength(0);
		            }
				} else if (node instanceof org.jsoup.nodes.TextNode) {
					String text = ((org.jsoup.nodes.TextNode)node).text();
					String[] arrayOfString1 = IIIlllII.split(text);
					Matcher localMatcher = IIIlllII.matcher(text);
					for (String str2 : arrayOfString1){
						 if (localMatcher.find()) {
							 str2 = str2 + localMatcher.group();
						 }
						 localStringBuffer.append(str2);
						 i += str2.length();
			             if (i >= 800){
			            	 contents.add(localStringBuffer.toString());
			                 i = 0;
			                 localStringBuffer.setLength(0);
			             }    
					}
				}
		    }
		    String localObject1 = localStringBuffer.toString();
		    if (StringUtils.isNotEmpty((String)localObject1)){
		    	contents.add(localObject1);
		    }
		}
		return (String[])contents.toArray(new String[contents.size()]);
	}
	
	public int getTotalPages(){
	    return getPageContents().length;
	}
	
	public String getText(){
		return Jsoup.parse(getContent()).text();
	}
	
	public String getPath() {
		Map<String,Object> localHashMap = Maps.newHashMap();
		localHashMap.put("id", getId());
		localHashMap.put("createDate", getCreateDate());
		localHashMap.put("title", getTitle());
		localHashMap.put("pageNumber", getPageNumber());
		return FreemarkerUtils.process(CmsUtils.getStaticPath("articleContent"), localHashMap);
	}
	
}

base-webapp-tab/src/main/webapp/WEB-INF/template/index.ftl
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8"/>
<meta http-equiv="Cache-Control" content="no-store" />
<meta http-equiv="Pragma" content="no-cache" />
<meta http-equiv="Expires" content="0" />
<meta name="author" content="http://thinkgem.iteye.com"/>
<meta http-equiv="X-UA-Compatible" content="IE=7,IE=9,IE=10" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<script src="${base}/static/jquery/jquery-1.8.3.min.js" type="text/javascript"></script>
<link href="${base}/static/modules/bootstrap/3.2.0/css/bootstrap.min.css" type="text/css" rel="stylesheet" />
<script src="${base}/static/modules/bootstrap/3.2.0/js/bootstrap.js" type="text/javascript"></script>
<link href="${base}/static/modules/cms/front/themes/basic/style.css" type="text/css" rel="stylesheet" />
<script type="text/javascript">
</script>
</head>
<body>
    [#include "/include/header.ftl"/]
    <div class="container" id="content" style="margin-top: 70px;">
		<div class="jumbotron">
	      <div class="container">
	        <h1>Hello, world!</h1>
	        <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
	        <p><a class="btn btn-primary btn-lg">Learn more »</a></p>
	      </div>
	    </div>
	    <div class="row">
	        <div class="col-md-3">
				<div class="list-group">
				  <a href="#" class="list-group-item disabled">热点分类</a>
				  [@category_root_list count = 3]
					  [#list categoryRoots as category]
						<a href="${frontBase}${category.path}" target="_blank" class="list-group-item">${category.name}</a>
					  [/#list]
				  [/@category_root_list]
				</div>
				
				<div class="list-group">
				  <a href="#" class="list-group-item disabled">热点文章</a>
				  <a href="#" class="list-group-item">精华文章 <span class="badge pull-right">42</span></a>
				  <a href="#" class="list-group-item">未解决问题</a>
				  <a href="#" class="list-group-item">商城动态</a>
				  <a href="#" class="list-group-item">用户评论</a>
				</div>
			</div>
			<div class="col-md-9">
				<ol class="breadcrumb">
				  <li><a href="${frontBase}">首页</a></li>
				  <li><a href="#">精华文章</a></li>
				  <li class="active">商城动态</li>
				</ol>
				<div class="result">
				   <ul>
						<li>
							<a href="/article/content/201306/27/1.html" title="五月靓丽女人节 呵护自己">五月靓丽女人节 呵护自己</a>
							<span title="2013-06-13 00:01:22">2013-06-13</span>
							<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 爱美的你是否早已按捺不住？五一过后就是热辣的夏天，我们为女性朋友们带来涵盖多种品牌的缤纷大促销，从鞋包到服装一应俱全，全面满足你的购物欲。4月27日至4月30日三天内，光临女人节，就有三重特惠供你选择，满199元减60元、满299...</p>
						</li>
						<li>
							<a href="/article/content/201306/28/1.html" title="电子商务未来是否需要“移动”">电子商务未来是否需要“移动”</a>
							<span title="2013-06-13 00:01:23">2013-06-13</span>
							<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2009年中，苹果公司市值超越谷歌；2010年5月，超越微软成为全球市值最高的科技公司；2012年8月12日，苹果市值超越石油巨头埃克森美孚，登顶全球市值榜首。一次次不断超越为我们展现的不仅是苹果公司活力与激情、动荡与辉煌相互交织的...</p>
						</li>
				   </ul>
				</div>
				<ul class="pagination">
				  <li class="disabled"><a href="#"><<</a></li>
				  <li class="active"><a href="#">1 <span class="sr-only">(current)</span></a></li>
				  <li class=""><a href="#">2 <span class="sr-only">(current)</span></a></li>
				  <li class=""><a href="#">3 <span class="sr-only">(current)</span></a></li>
				  <li class=""><a href="#">4 <span class="sr-only">(current)</span></a></li>
				  <li class=""><a href="#">5 <span class="sr-only">(current)</span></a></li>
				  <li class=""><a href="#">6 <span class="sr-only">(current)</span></a></li>
				  <li><a href="#">>></a></li>
				</ul>
			</div>
	    </div>
    </div>
    [#include "/include/footer.ftl"/]
</body>
</html>